#!/bin/sh

result=$(fvm flutter analyze --no-fatal-infos --no-fatal-warnings)
exitCode=$? # If the exitCode is zero, then command executed successfully.

if [ $exitCode  -ne 0 ]; then
  echo "$result"
  echo "Flutter analyze found issues, please fix them."
  exit 1
fi
echo "Finished running flutter analyze command."

################################################################

# 2. Run `dart dry --apply` to auto-fix basic issues.
result=$(fvm dart fix --apply)
exitCode=$?

# Adding the files updated by `dart fix` command to git.
git add .

echo "$result"

if [ $exitCode -ne 0 ]; then
  echo "dart fix command failed to execute."
  exit 1
fi
echo "Finished running dart fix command."