#!/bin/sh

### Flutter analyze
result=$(fvm flutter analyze --no-fatal-infos --no-fatal-warnings)
exitCode=$?

if [ $exitCode  -ne 0 ]; then
  echo "$result"
  echo "Flutter analyze found issues, please fix them."
  exit 1
fi
echo "Finished running flutter analyze command."

################################################################

### Flutter tests
result=$(fvm flutter test)
exitCode=$?

if [ $exitCode  -ne 0 ]; then
  echo "$result"
  echo "Flutter tests failed"
  exit 1
fi
echo "Finished running flutter test command."

################################################################

### Dart fix
result=$(fvm dart fix --apply)
exitCode=$?

git add .

echo "$result"

if [ $exitCode -ne 0 ]; then
  echo "Dart fix command failed to execute."
  exit 1
fi
echo "Finished running dart fix command."